### PR TITLE
Add editor

### LINKED ISSUE #8: Customize BodyPix Params
Hey, really awesome project!

It'd be neat if there was an interface on the website to allow users to customize the parameters passed into `bodyPix.load`, so that they can use a better/worse model depending on what they need. And it'd allow them to mess around with settings to find one that works best.

If you think it's a good idea, I can take a look at making a PR.

### PR DESCRIPTION
**Pull request by clee-ai**
You can try out the editor file, it should allow you to change all parameters of the model. It'll spit out a url that you can then use for the "player.html" which you input into OBS. I'll check for bugs and update the docs later 👍 Works great for me in OBS.

Let me know what you think!

### CODE REVIEW

**Review by nhtua — CHANGES_REQUESTED** [review]
Beautiful, my friend! It's very basic controler but it works. Let merge first and improve later. 
Here are my suggestions. 
- To serve the app from greencam.netlify.app, we still need an `index.html`, so rename `editor.html ` -> `index.html` It should runs as the default page
- URL output should be a link instead of Input. As a text box, it forces me to select all and copy. If it's just a link, I can copy immediately.

**Comment by clee-ai** [comment]
In #6 he changes the netowrk to `segmentMultiPerson`, I reverted it back in this PR but I'm curious what the usecase is for that instead of segmentPerson. Segmentperson should still detect multiple people and create a single mask, and it will be faster.

**Comment by nhtua** [comment]
Double-checked [the official document](https://github.com/tensorflow/tfjs-models/blob/master/body-pix/README.md#person-segmentation).
> Given an image with one or more people, person segmentation predicts segmentation for all people together. It returns a 
> PersonSegmentation object corresponding to segmentation for people in the image. It does not disambiguate between different
> individuals. If you need to segment individuals separately use segmentMultiPerson (the caveat is this method is slower).

You're right! I guess **edurenye** was confused by the name segmentMultiPerson. Multi here is not about "people" but it's is multi segments data. In GreenCam, we don't actually need `segmentMultiPerson`.

**Comment by clee-ai** [comment]
@nhtua I updated with the changes, let me know your thoughts. In the future I can improve the UI and make some other tweaks, but it's functional for now.

**Review by nhtua — APPROVED** [review]

**Comment by nhtua** [comment]
Tested, It works wells. I'm going to merge now. I will rewrite some document later.

**Pull request merged**
